# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: ofLiberty
title_1: of
title_2: Liberty

slug: Planning Your Dream Greenhouse
description: >- # this means to ignore newlines until "baseurl:"
  Description
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://greenhouse.planning.solar" # the base hostname & protocol for your site, e.g. http://example.com
brand_url: https://solarinnovations.com

# Analytics
# gtm_id: GTM-MCG4RJC


# Dev Details
email: ndkline@theagora.us
twitter_username: ndkline
github: false
github_username:  ndkline
github_url: https://github.com/TheAgora/ofliberty




sitemap:
    filename: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/index.html"
    change_frequency_name: "change_frequency"
    priority_name: "priority"






# Resources
# resources:
#   - {title: Greenhouse Location Recommendations, path: /assets/pdf/Greenhouse-Reccomendations-Based-on-Location.pdf}
#   - {title: Greenhouse Planning Worksheet, path: /assets/pdf/Greenhouse-Planning-Worksheet.pdf}
#   - {title: Greenhouse Accessories, path: /assets/pdf/Greenhouse-Accessories.pdf}

# Home
vertical_height: 100 # Only supports 100 right now -- TODO
cta_gs_url: /types

# Blog
permalink: /blog/:year/:month/:day/:title.html

# Footer Settings
footer-cta-text: Ready?
footer-cta-link-text: Get Started
footer-cta-link-url: /types/
footer-cta-link-target: _blank
footer-brand_img_url: /assets/images/white-horizontal.svg
footer-brand_img_alt: ccc
footer-brand_url: xxx


## Social Accounts
facebook: x
twitter: x
pinterest: x
instagram: x
houzz: x
linkedin: x
youtube: x   # channel ID
google_plus: x

# Build settings
sass:
  style: compressed
# minify_html: false
markdown: kramdown
destination: docs
theme: solar-flair
theme_style: two # Use 'grey' and not 'gray'
asset_cdn: 1 # 0 = no  |  1 = yes, unminified  |  2 = yes, minified
plugins:
  - jekyll-feed
  # - jekyll-toc

collections:
  footer-nav:
output: false
